version: '3.10'

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: fastapi_service
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/api/models
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
